/* Generated By:JJTree&JavaCC: Do not edit this line. ExpressionParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
#ifndef EXPRESSIONPARSERCONSTANTS_H
#define EXPRESSIONPARSERCONSTANTS_H
#include "JavaCC.h"

  /** End of File. */
const  int _EOF = 0;
  /** RegularExpression Id. */
const  int SINGLE_LINE_COMMENT = 8;
  /** RegularExpression Id. */
const  int MULTI_LINE_COMMENT = 9;
  /** RegularExpression Id. */
const  int OR = 11;
  /** RegularExpression Id. */
const  int AND = 12;
  /** RegularExpression Id. */
const  int NOT = 13;
  /** RegularExpression Id. */
const  int BITWISE_OR = 14;
  /** RegularExpression Id. */
const  int BITWISE_XOR = 15;
  /** RegularExpression Id. */
const  int BITWISE_AND = 16;
  /** RegularExpression Id. */
const  int BITWISE_NOT = 17;
  /** RegularExpression Id. */
const  int TRUE = 18;
  /** RegularExpression Id. */
const  int FALSE = 19;
  /** RegularExpression Id. */
const  int NULL = 20;
  /** RegularExpression Id. */
const  int INTEGER_LITERAL = 21;
  /** RegularExpression Id. */
const  int HEX_LITERAL = 22;
  /** RegularExpression Id. */
const  int DECIMAL_LITERAL = 23;
  /** RegularExpression Id. */
const  int OCTAL_LITERAL = 24;
  /** RegularExpression Id. */
const  int BINARY_LITERAL = 25;
  /** RegularExpression Id. */
const  int FLOATING_POINT_LITERAL = 26;
  /** RegularExpression Id. */
const  int EXPONENT = 27;
  /** RegularExpression Id. */
const  int STRING_LITERAL = 28;
  /** RegularExpression Id. */
const  int PLUS = 29;
  /** RegularExpression Id. */
const  int MINUS = 30;
  /** RegularExpression Id. */
const  int MUL = 31;
  /** RegularExpression Id. */
const  int DIV = 32;
  /** RegularExpression Id. */
const  int MOD = 33;
  /** RegularExpression Id. */
const  int QUESTION = 34;
  /** RegularExpression Id. */
const  int COLON = 35;
  /** RegularExpression Id. */
const  int COMMA = 36;
  /** RegularExpression Id. */
const  int EQ = 37;
  /** RegularExpression Id. */
const  int NE = 38;
  /** RegularExpression Id. */
const  int MATCH = 39;
  /** RegularExpression Id. */
const  int LT = 40;
  /** RegularExpression Id. */
const  int GT = 41;
  /** RegularExpression Id. */
const  int LTE = 42;
  /** RegularExpression Id. */
const  int GTE = 43;
  /** RegularExpression Id. */
const  int LBRAKET = 44;
  /** RegularExpression Id. */
const  int RBRAKET = 45;
  /** RegularExpression Id. */
const  int LBRACE = 46;
  /** RegularExpression Id. */
const  int RBRACE = 47;
  /** RegularExpression Id. */
const  int RIGHT_SHIFT = 48;
  /** RegularExpression Id. */
const  int URIGHT_SHIFT = 49;
  /** RegularExpression Id. */
const  int LEFT_SHIFT = 50;
  /** RegularExpression Id. */
const  int IDENTIFIER = 51;
  /** RegularExpression Id. */
const  int URICHAR = 52;
  /** RegularExpression Id. */
const  int LETTER = 53;
  /** RegularExpression Id. */
const  int DIGIT = 54;

  /** Lexical state. */
const  int DEFAULT = 0;
  /** Lexical state. */
const  int IN_SINGLE_LINE_COMMENT = 1;
  /** Lexical state. */
const  int IN_MULTI_LINE_COMMENT = 2;

  /** Literal token values. */
  static JAVACC_CHAR_TYPE tokenImage_arr_0[] = 
{0x3c, 0x45, 0x4f, 0x46, 0x3e, 0};
  static JAVACC_CHAR_TYPE tokenImage_arr_1[] = 
{0x22, 0x20, 0x22, 0};
  static JAVACC_CHAR_TYPE tokenImage_arr_2[] = 
{0x22, 0x9, 0x22, 0};
  static JAVACC_CHAR_TYPE tokenImage_arr_3[] = 
{0x22, 0xa, 0x22, 0};
  static JAVACC_CHAR_TYPE tokenImage_arr_4[] = 
{0x22, 0xd, 0x22, 0};
  static JAVACC_CHAR_TYPE tokenImage_arr_5[] = 
{0x22, 0x3c, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x20, 0x6f, 0x66, 0x20, 0x6b, 0x69, 0x6e, 0x64, 0x20, 0x35, 0x3e, 0x22, 0};
  static JAVACC_CHAR_TYPE tokenImage_arr_6[] = 
{0x22, 0x2f, 0x2f, 0x22, 0};
  static JAVACC_CHAR_TYPE tokenImage_arr_7[] = 
{0x22, 0x2f, 0x2a, 0x22, 0};
  static JAVACC_CHAR_TYPE tokenImage_arr_8[] = 
{0x22, 0x3c, 0x53, 0x49, 0x4e, 0x47, 0x4c, 0x45, 0x5f, 0x4c, 0x49, 0x4e, 0x45, 0x5f, 0x43, 0x4f, 0x4d, 0x4d, 0x45, 0x4e, 0x54, 0x3e, 0x22, 0};
  static JAVACC_CHAR_TYPE tokenImage_arr_9[] = 
{0x22, 0x2a, 0x2f, 0x22, 0};
  static JAVACC_CHAR_TYPE tokenImage_arr_10[] = 
{0x22, 0x3c, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x20, 0x6f, 0x66, 0x20, 0x6b, 0x69, 0x6e, 0x64, 0x20, 0x31, 0x30, 0x3e, 0x22, 0};
  static JAVACC_CHAR_TYPE tokenImage_arr_11[] = 
{0x22, 0x7c, 0x7c, 0x22, 0};
  static JAVACC_CHAR_TYPE tokenImage_arr_12[] = 
{0x22, 0x26, 0x26, 0x22, 0};
  static JAVACC_CHAR_TYPE tokenImage_arr_13[] = 
{0x22, 0x21, 0x22, 0};
  static JAVACC_CHAR_TYPE tokenImage_arr_14[] = 
{0x22, 0x7c, 0x22, 0};
  static JAVACC_CHAR_TYPE tokenImage_arr_15[] = 
{0x22, 0x5e, 0x22, 0};
  static JAVACC_CHAR_TYPE tokenImage_arr_16[] = 
{0x22, 0x26, 0x22, 0};
  static JAVACC_CHAR_TYPE tokenImage_arr_17[] = 
{0x22, 0x7e, 0x22, 0};
  static JAVACC_CHAR_TYPE tokenImage_arr_18[] = 
{0x22, 0x54, 0x52, 0x55, 0x45, 0x22, 0};
  static JAVACC_CHAR_TYPE tokenImage_arr_19[] = 
{0x22, 0x46, 0x41, 0x4c, 0x53, 0x45, 0x22, 0};
  static JAVACC_CHAR_TYPE tokenImage_arr_20[] = 
{0x22, 0x4e, 0x55, 0x4c, 0x4c, 0x22, 0};
  static JAVACC_CHAR_TYPE tokenImage_arr_21[] = 
{0x22, 0x3c, 0x49, 0x4e, 0x54, 0x45, 0x47, 0x45, 0x52, 0x5f, 0x4c, 0x49, 0x54, 0x45, 0x52, 0x41, 0x4c, 0x3e, 0x22, 0};
  static JAVACC_CHAR_TYPE tokenImage_arr_22[] = 
{0x22, 0x3c, 0x48, 0x45, 0x58, 0x5f, 0x4c, 0x49, 0x54, 0x45, 0x52, 0x41, 0x4c, 0x3e, 0x22, 0};
  static JAVACC_CHAR_TYPE tokenImage_arr_23[] = 
{0x22, 0x3c, 0x44, 0x45, 0x43, 0x49, 0x4d, 0x41, 0x4c, 0x5f, 0x4c, 0x49, 0x54, 0x45, 0x52, 0x41, 0x4c, 0x3e, 0x22, 0};
  static JAVACC_CHAR_TYPE tokenImage_arr_24[] = 
{0x22, 0x3c, 0x4f, 0x43, 0x54, 0x41, 0x4c, 0x5f, 0x4c, 0x49, 0x54, 0x45, 0x52, 0x41, 0x4c, 0x3e, 0x22, 0};
  static JAVACC_CHAR_TYPE tokenImage_arr_25[] = 
{0x22, 0x3c, 0x42, 0x49, 0x4e, 0x41, 0x52, 0x59, 0x5f, 0x4c, 0x49, 0x54, 0x45, 0x52, 0x41, 0x4c, 0x3e, 0x22, 0};
  static JAVACC_CHAR_TYPE tokenImage_arr_26[] = 
{0x22, 0x3c, 0x46, 0x4c, 0x4f, 0x41, 0x54, 0x49, 0x4e, 0x47, 0x5f, 0x50, 0x4f, 0x49, 0x4e, 0x54, 0x5f, 0x4c, 0x49, 0x54, 0x45, 0x52, 0x41, 0x4c, 0x3e, 0x22, 0};
  static JAVACC_CHAR_TYPE tokenImage_arr_27[] = 
{0x22, 0x3c, 0x45, 0x58, 0x50, 0x4f, 0x4e, 0x45, 0x4e, 0x54, 0x3e, 0x22, 0};
  static JAVACC_CHAR_TYPE tokenImage_arr_28[] = 
{0x22, 0x3c, 0x53, 0x54, 0x52, 0x49, 0x4e, 0x47, 0x5f, 0x4c, 0x49, 0x54, 0x45, 0x52, 0x41, 0x4c, 0x3e, 0x22, 0};
  static JAVACC_CHAR_TYPE tokenImage_arr_29[] = 
{0x22, 0x2b, 0x22, 0};
  static JAVACC_CHAR_TYPE tokenImage_arr_30[] = 
{0x22, 0x2d, 0x22, 0};
  static JAVACC_CHAR_TYPE tokenImage_arr_31[] = 
{0x22, 0x2a, 0x22, 0};
  static JAVACC_CHAR_TYPE tokenImage_arr_32[] = 
{0x22, 0x2f, 0x22, 0};
  static JAVACC_CHAR_TYPE tokenImage_arr_33[] = 
{0x22, 0x25, 0x22, 0};
  static JAVACC_CHAR_TYPE tokenImage_arr_34[] = 
{0x22, 0x3f, 0x22, 0};
  static JAVACC_CHAR_TYPE tokenImage_arr_35[] = 
{0x22, 0x3a, 0x22, 0};
  static JAVACC_CHAR_TYPE tokenImage_arr_36[] = 
{0x22, 0x2c, 0x22, 0};
  static JAVACC_CHAR_TYPE tokenImage_arr_37[] = 
{0x22, 0x3d, 0x3d, 0x22, 0};
  static JAVACC_CHAR_TYPE tokenImage_arr_38[] = 
{0x22, 0x21, 0x3d, 0x22, 0};
  static JAVACC_CHAR_TYPE tokenImage_arr_39[] = 
{0x22, 0x7e, 0x3d, 0x22, 0};
  static JAVACC_CHAR_TYPE tokenImage_arr_40[] = 
{0x22, 0x3c, 0x22, 0};
  static JAVACC_CHAR_TYPE tokenImage_arr_41[] = 
{0x22, 0x3e, 0x22, 0};
  static JAVACC_CHAR_TYPE tokenImage_arr_42[] = 
{0x22, 0x3c, 0x3d, 0x22, 0};
  static JAVACC_CHAR_TYPE tokenImage_arr_43[] = 
{0x22, 0x3e, 0x3d, 0x22, 0};
  static JAVACC_CHAR_TYPE tokenImage_arr_44[] = 
{0x22, 0x28, 0x22, 0};
  static JAVACC_CHAR_TYPE tokenImage_arr_45[] = 
{0x22, 0x29, 0x22, 0};
  static JAVACC_CHAR_TYPE tokenImage_arr_46[] = 
{0x22, 0x7b, 0x22, 0};
  static JAVACC_CHAR_TYPE tokenImage_arr_47[] = 
{0x22, 0x7d, 0x22, 0};
  static JAVACC_CHAR_TYPE tokenImage_arr_48[] = 
{0x22, 0x3e, 0x3e, 0x22, 0};
  static JAVACC_CHAR_TYPE tokenImage_arr_49[] = 
{0x22, 0x3e, 0x3e, 0x3e, 0x22, 0};
  static JAVACC_CHAR_TYPE tokenImage_arr_50[] = 
{0x22, 0x3c, 0x3c, 0x22, 0};
  static JAVACC_CHAR_TYPE tokenImage_arr_51[] = 
{0x22, 0x3c, 0x49, 0x44, 0x45, 0x4e, 0x54, 0x49, 0x46, 0x49, 0x45, 0x52, 0x3e, 0x22, 0};
  static JAVACC_CHAR_TYPE tokenImage_arr_52[] = 
{0x22, 0x3c, 0x55, 0x52, 0x49, 0x43, 0x48, 0x41, 0x52, 0x3e, 0x22, 0};
  static JAVACC_CHAR_TYPE tokenImage_arr_53[] = 
{0x22, 0x3c, 0x4c, 0x45, 0x54, 0x54, 0x45, 0x52, 0x3e, 0x22, 0};
  static JAVACC_CHAR_TYPE tokenImage_arr_54[] = 
{0x22, 0x3c, 0x44, 0x49, 0x47, 0x49, 0x54, 0x3e, 0x22, 0};
  static JAVACC_STRING_TYPE tokenImage[] = {
tokenImage_arr_0, 
tokenImage_arr_1, 
tokenImage_arr_2, 
tokenImage_arr_3, 
tokenImage_arr_4, 
tokenImage_arr_5, 
tokenImage_arr_6, 
tokenImage_arr_7, 
tokenImage_arr_8, 
tokenImage_arr_9, 
tokenImage_arr_10, 
tokenImage_arr_11, 
tokenImage_arr_12, 
tokenImage_arr_13, 
tokenImage_arr_14, 
tokenImage_arr_15, 
tokenImage_arr_16, 
tokenImage_arr_17, 
tokenImage_arr_18, 
tokenImage_arr_19, 
tokenImage_arr_20, 
tokenImage_arr_21, 
tokenImage_arr_22, 
tokenImage_arr_23, 
tokenImage_arr_24, 
tokenImage_arr_25, 
tokenImage_arr_26, 
tokenImage_arr_27, 
tokenImage_arr_28, 
tokenImage_arr_29, 
tokenImage_arr_30, 
tokenImage_arr_31, 
tokenImage_arr_32, 
tokenImage_arr_33, 
tokenImage_arr_34, 
tokenImage_arr_35, 
tokenImage_arr_36, 
tokenImage_arr_37, 
tokenImage_arr_38, 
tokenImage_arr_39, 
tokenImage_arr_40, 
tokenImage_arr_41, 
tokenImage_arr_42, 
tokenImage_arr_43, 
tokenImage_arr_44, 
tokenImage_arr_45, 
tokenImage_arr_46, 
tokenImage_arr_47, 
tokenImage_arr_48, 
tokenImage_arr_49, 
tokenImage_arr_50, 
tokenImage_arr_51, 
tokenImage_arr_52, 
tokenImage_arr_53, 
tokenImage_arr_54, 
  };

#endif
