#pragma once

#include <boost/shared_ptr.hpp>

class DataTable;
class FormatConverter;
class ClassicEncodingSettings;
class Data;
class AgObject;
class AgClass;
class TableFormat;
class DataRecord;
class DataTableQuery;
class FieldFormat;
class Evaluator;
class Expression;
class DataTableSorter;
class TableKeyFieldsValidator;
class RecordValidator;
class TableValidator;
class Binding;
class Reference;
class QueryCondition;
class EvaluationEnvironment;


typedef boost::shared_ptr<AgObject> AgObjectPtr;
typedef boost::shared_ptr<AgClass> AgClassPtr;
typedef boost::shared_ptr<TableFormat> TableFormatPtr;
typedef boost::shared_ptr<DataTable> DataTablePtr;
typedef boost::shared_ptr<DataRecord> DataRecordPtr;
typedef boost::shared_ptr<FieldFormat> FieldFormatPtr;
typedef boost::shared_ptr<FormatConverter> FormatConverterPtr;
typedef boost::shared_ptr<ClassicEncodingSettings> ClassicEncodingSettingsPtr;
typedef boost::shared_ptr<Data> DataPtr;
typedef boost::shared_ptr<Evaluator> EvaluatorPtr;
typedef boost::shared_ptr<Expression> ExpressionPtr;
typedef boost::shared_ptr<DataTableQuery> DataTableQueryPtr;
typedef boost::shared_ptr<DataTableSorter> DataTableSorterPtr;
typedef boost::shared_ptr<TableKeyFieldsValidator> TableKeyFieldsValidatorPtr;
typedef boost::shared_ptr<RecordValidator> RecordValidatorPtr;
typedef boost::shared_ptr<TableValidator> TableValidatorPtr;
typedef boost::shared_ptr<Binding> BindingPtr;
typedef boost::shared_ptr<Reference> ReferencePtr;
typedef boost::shared_ptr<QueryCondition> QueryConditionPtr;
typedef boost::shared_ptr<EvaluationEnvironment> EvaluationEnvironmentPtr;



class CallerController;
class CallerData;
class Permission;
class Permissions;
class PermissionCache;
class Date;
class ContextManager;
class Context;
class VariableData;
class PermissionChecker;
class FunctionData;
class VariableDefinition;
class EventDataPtr;
class ActionDefinition;
class ContextStatus;
class ContextVisitor;
class VariableStatus;
class RequestController;
class EventProcessingRule;
class ContextEventListener;
class Event;
class RequestIdentifier;
class ActionResponse;
class ActionCommand;
class GroupIdentifier;
class BatchEntry;
class Enrichment;
class ActionContext;
class FunctionDefinition;
class Acknowledgement;
class InitialRequest;
class EventDefinition;
class BatchContext;
class ActionManager;
class RequestCache;
class ActionIdentifier;
class ActionState;
class ActionResult;
class FireEventRequestController;
class ActionIdGenerator;
class Context;
class PersistenceBinding;
class PersistenceOptions;
class FunctionImplementation;
class GenericActionResponse;
class ActionInitializer;
class Expression;
class ServerActionInput;
class ActionExecutionMode;
class GenericActionCommand;
class ErrorCollector;
class WindowLocation;
class DashboardProperties;
class Action;
class ActionDirectory;
//class ;
//class ;
//class ;
//class ;
//class ;
//class ;
//class ;
//class ;

typedef boost::shared_ptr<CallerController>  CallerControllerPtr;
typedef boost::shared_ptr<CallerData>  CallerDataPtr;
typedef boost::shared_ptr<Permission>  PermissionPtr;
typedef boost::shared_ptr<Permissions>  PermissionsPtr;
typedef boost::shared_ptr<PermissionCache>  PermissionCachePtr;
typedef boost::shared_ptr<Date>  DatePtr;
typedef boost::shared_ptr<ContextManager> ContextManagerPtr;
typedef boost::shared_ptr<Context> ContextPtr;
typedef boost::shared_ptr<VariableData> VariableDataPtr;
typedef boost::shared_ptr<PermissionChecker>  PermissionCheckerPtr;
typedef boost::shared_ptr<FunctionData> FunctionDataPtr;
typedef boost::shared_ptr<VariableDefinition> VariableDefinitionPtr;
typedef boost::shared_ptr<EventDataPtr> EventDataPtrPtr;
typedef boost::shared_ptr<ActionDefinition> ActionDefinitionPtr;
typedef boost::shared_ptr<ContextStatus> ContextStatusPtr;
typedef boost::shared_ptr<ContextVisitor> ContextVisitorPtr;
typedef boost::shared_ptr<VariableStatus> VariableStatusPtr;
typedef boost::shared_ptr<RequestController> RequestControllerPtr;
typedef boost::shared_ptr<EventProcessingRule> EventProcessingRulePtr;
typedef boost::shared_ptr<ContextEventListener> ContextEventListenerPtr;
typedef boost::shared_ptr<Event> EventPtr;
typedef boost::shared_ptr<RequestIdentifier> RequestIdentifierPtr;
typedef boost::shared_ptr<ActionResponse> ActionResponsePtr;
typedef boost::shared_ptr<ActionCommand> ActionCommandPtr;
typedef boost::shared_ptr<GroupIdentifier> GroupIdentifierPtr;
typedef boost::shared_ptr<BatchEntry> BatchEntryPtr;
typedef boost::shared_ptr<Enrichment> EnrichmentPtr;
typedef boost::shared_ptr<ActionContext> ActionContextPtr;
typedef boost::shared_ptr<FunctionDefinition> FunctionDefinitionPtr;
typedef boost::shared_ptr<Acknowledgement> AcknowledgementPtr;
typedef boost::shared_ptr<InitialRequest> InitialRequestPtr;
typedef boost::shared_ptr<EventDefinition> EventDefinitionPtr;
typedef boost::shared_ptr<BatchContext> BatchContextPtr;
typedef boost::shared_ptr<ActionManager> ActionManagerPtr;
typedef boost::shared_ptr<RequestCache> RequestCachePtr;
typedef boost::shared_ptr<ActionIdentifier> ActionIdentifierPtr;
typedef boost::shared_ptr<ActionState> ActionStatePtr;
typedef boost::shared_ptr<ActionResult> ActionResultPtr;
typedef boost::shared_ptr<FireEventRequestController> FireEventRequestControllerPtr;
typedef boost::shared_ptr<ActionIdGenerator> ActionIdGeneratorPtr;
typedef boost::shared_ptr<Context> ContextPtr;
typedef boost::shared_ptr<PersistenceBinding> PersistenceBindingPtr;
typedef boost::shared_ptr<PersistenceOptions> PersistenceOptionsPtr;
typedef boost::shared_ptr<FunctionImplementation> FunctionImplementationPtr;
typedef boost::shared_ptr<GenericActionResponse> GenericActionResponsePtr;
typedef boost::shared_ptr<ActionInitializer> ActionInitializerPtr;
typedef boost::shared_ptr<Expression> ExpressionPtr;
typedef boost::shared_ptr<ServerActionInput> ServerActionInputPtr;
typedef boost::shared_ptr<ActionExecutionMode> ActionExecutionModePtr;
typedef boost::shared_ptr<GenericActionCommand> GenericActionCommandPtr;
typedef boost::shared_ptr<ErrorCollector> ErrorCollectorPtr;
typedef boost::shared_ptr<WindowLocation> WindowLocationPtr;
typedef boost::shared_ptr<DashboardProperties> DashboardPropertiesPtr;
typedef boost::shared_ptr<Action> ActionPtr;
typedef boost::shared_ptr<ActionDirectory> ActionDirectoryPtr;
//typedef boost::shared_ptr<>;
//typedef boost::shared_ptr<>;
//typedef boost::shared_ptr<>;
