#pragma once
#ifndef PointersH
#define PointersH

#include <boost/shared_ptr.hpp>

class DataTable;
class FormatConverter;
class ClassicEncodingSettings;
class Data;
class AgObject;
class AgClass;
class TableFormat;
class DataRecord;
class DataTableQuery;
class FieldFormat;
//class FieldValidator;
class Evaluator;
class Expression;
class DataTableSorter;
class TableKeyFieldsValidator;
class RecordValidator;
class TableValidator;
class Binding;
class Reference;
class QueryCondition;
class EvaluationEnvironment;


typedef boost::shared_ptr<AgObject> AgObjectPtr;
typedef boost::shared_ptr<AgClass> AgClassPtr;
typedef boost::shared_ptr<TableFormat> TableFormatPtr;
typedef boost::shared_ptr<DataTable> DataTablePtr;
typedef boost::shared_ptr<DataRecord> DataRecordPtr;
typedef boost::shared_ptr<FieldFormat> FieldFormatPtr;
//typedef boost::shared_ptr<FieldValidator> FieldValidatorPtr;
typedef boost::shared_ptr<FormatConverter> FormatConverterPtr;
typedef boost::shared_ptr<ClassicEncodingSettings> ClassicEncodingSettingsPtr;
typedef boost::shared_ptr<Data> DataPtr;
typedef boost::shared_ptr<Evaluator> EvaluatorPtr;
typedef boost::shared_ptr<Expression> ExpressionPtr;
typedef boost::shared_ptr<DataTableQuery> DataTableQueryPtr;
typedef boost::shared_ptr<DataTableSorter> DataTableSorterPtr;
typedef boost::shared_ptr<TableKeyFieldsValidator> TableKeyFieldsValidatorPtr;
typedef boost::shared_ptr<RecordValidator> RecordValidatorPtr;
typedef boost::shared_ptr<TableValidator> TableValidatorPtr;
typedef boost::shared_ptr<Binding> BindingPtr;
typedef boost::shared_ptr<Reference> ReferencePtr;
typedef boost::shared_ptr<QueryCondition> QueryConditionPtr;
typedef boost::shared_ptr<EvaluationEnvironment> EvaluationEnvironmentPtr;



class CallerController;
class CallerData;
class Permission;
class Permissions;
class PermissionCache;
class Date;
class ContextManager;
class Context;
class VariableData;
class PermissionChecker;
class FunctionData;
class VariableDefinition;
class EventData;
class ActionDefinition;
class ContextStatus;
class ContextVisitor;
class VariableStatus;
class RequestController;
class EventProcessingRule;
class ContextEventListener;
class Event;
class RequestIdentifier;
class ActionResponse;
class ActionCommand;
class GroupIdentifier;
class BatchEntry;
class Enrichment;
class ActionContext;
class FunctionDefinition;
class Acknowledgement;
class InitialRequest;
class EventDefinition;
class BatchContext;
class ActionManager;
class RequestCache;
class ActionIdentifier;
class ActionState;
class ActionResult;
class FireEventRequestController;
class ActionIdGenerator;
class Context;
class PersistenceBinding;
class PersistenceOptions;
class FunctionImplementation;
class GenericActionResponse;
class ActionInitializer;
class Expression;
class ServerActionInput;
class ActionExecutionMode;
class GenericActionCommand;
class ErrorCollector;
class WindowLocation;
class DashboardProperties;
class Action;
class ActionDirectory;
class VariableGetter;
class VariableSetter;
class EventEnrichmentRule;
class GenericActionResponse;
class GenericActionCommand;
class ActionLocator;
class ActionExecutionMode;
//template <class L> class ActionDirectory;
class ServerActionInput;
class ErrorCollector;
class ActionInitializer;
template <class T> class ResourceMask;
class BasicActionDefinition;
class BatchAction;
class TreeMask;
class EntityReference;
class WindowLocation;
class DashboardProperties;
class ResourceBundle;
class Locale;
class OutgoingAggreGateCommand;
class ContextEventListenerInfo;
class CommandParser;
class IncomingAggreGateCommand;
class BlockingChannel;
class ContextEventListenerSet;
class PermissionType;
class RemoteServer;
class AgentContext;
class AgentContextManager;
class BindingProvider;
class CallerControllerSelector;
class ChangeCache;
class BindingProcessor;
class EvaluationOptions;
class ReferenceListener;
class Exception;
class Command;
class CommandParserListener;
template <class I,class O> class AbstractDeviceController;
class CommandProcessorStatistics;
template <class I,class O,class C> class  AsyncCommandProcessor;
class PluginDirector;
class GroupContext;
class DeviceAssetDefinition;
class DeviceContext;
class SynchronizationParameters;
class SettingSynchronizationOptions;
class DeviceSettingStatus;
class SynchronizationHandler;
class Color;
class ReferenceWriter;
class SynchronizationResult;
class DiscoveryProvider;
class DeviceRecommendation;
class DiscoverableServiceDefinition;
class DiscoveryResultItem;
class DiscoverableService;
class ServerContext;
class BasePlugin;
class AggreGateDevice;
class UserSettings;
class FormatCache;
class RemoteContextManager;
class EntityRelatedActionDescriptor;
template <class D,class C> class AbstractAggreGateDeviceController;
template <class C> class ProxyContext;
class EntityRelatedActionDescriptor;
class URI;
class EditDataMerger;
class DashboardProperties;
class EntityList;
class ExecutorService;
class EventDispatcher;
class CompatibilityConverter;
class ReferenceWriter;
class UncheckedCallerController;
class ExpressionParserVisitor;
class DefaultRequestController;
class ReferencesFinderVisitor;
class ExpressionParser;
//class ;
//class ;
//class ;
//class ;
//class ;
//class ;
//class ;
//class ;
//class ;
//class ;
//class ;
//class ;
//class ;
//class ;

typedef boost::shared_ptr<CallerController>  CallerControllerPtr;
typedef boost::shared_ptr<CallerData>  CallerDataPtr;
typedef boost::shared_ptr<Permission>  PermissionPtr;
typedef boost::shared_ptr<Permissions>  PermissionsPtr;
typedef boost::shared_ptr<PermissionCache>  PermissionCachePtr;
typedef boost::shared_ptr<Date>  DatePtr;
typedef boost::shared_ptr<ContextManager> ContextManagerPtr;
typedef boost::shared_ptr<Context> ContextPtr;
typedef boost::shared_ptr<VariableData> VariableDataPtr;
typedef boost::shared_ptr<PermissionChecker>  PermissionCheckerPtr;
typedef boost::shared_ptr<FunctionData> FunctionDataPtr;
typedef boost::shared_ptr<VariableDefinition> VariableDefinitionPtr;
typedef boost::shared_ptr<EventData> EventDataPtr;
typedef boost::shared_ptr<ActionDefinition> ActionDefinitionPtr;
typedef boost::shared_ptr<ContextStatus> ContextStatusPtr;
typedef boost::shared_ptr<ContextVisitor> ContextVisitorPtr;
typedef boost::shared_ptr<VariableStatus> VariableStatusPtr;
typedef boost::shared_ptr<RequestController> RequestControllerPtr;
typedef boost::shared_ptr<EventProcessingRule> EventProcessingRulePtr;
typedef boost::shared_ptr<ContextEventListener> ContextEventListenerPtr;
typedef boost::shared_ptr<Event> EventPtr;
typedef boost::shared_ptr<RequestIdentifier> RequestIdentifierPtr;
typedef boost::shared_ptr<ActionResponse> ActionResponsePtr;
typedef boost::shared_ptr<ActionCommand> ActionCommandPtr;
typedef boost::shared_ptr<GroupIdentifier> GroupIdentifierPtr;
typedef boost::shared_ptr<BatchEntry> BatchEntryPtr;
typedef boost::shared_ptr<Enrichment> EnrichmentPtr;
typedef boost::shared_ptr<ActionContext> ActionContextPtr;
typedef boost::shared_ptr<FunctionDefinition> FunctionDefinitionPtr;
typedef boost::shared_ptr<Acknowledgement> AcknowledgementPtr;
typedef boost::shared_ptr<InitialRequest> InitialRequestPtr;
typedef boost::shared_ptr<EventDefinition> EventDefinitionPtr;
typedef boost::shared_ptr<BatchContext> BatchContextPtr;
typedef boost::shared_ptr<ActionManager> ActionManagerPtr;
typedef boost::shared_ptr<RequestCache> RequestCachePtr;
typedef boost::shared_ptr<ActionIdentifier> ActionIdentifierPtr;
typedef boost::shared_ptr<ActionState> ActionStatePtr;
typedef boost::shared_ptr<ActionResult> ActionResultPtr;
typedef boost::shared_ptr<FireEventRequestController> FireEventRequestControllerPtr;
typedef boost::shared_ptr<ActionIdGenerator> ActionIdGeneratorPtr;
typedef boost::shared_ptr<Context> ContextPtr;
typedef boost::shared_ptr<PersistenceBinding> PersistenceBindingPtr;
typedef boost::shared_ptr<PersistenceOptions> PersistenceOptionsPtr;
typedef boost::shared_ptr<FunctionImplementation> FunctionImplementationPtr;
typedef boost::shared_ptr<GenericActionResponse> GenericActionResponsePtr;
typedef boost::shared_ptr<ActionInitializer> ActionInitializerPtr;
typedef boost::shared_ptr<Expression> ExpressionPtr;
typedef boost::shared_ptr<ServerActionInput> ServerActionInputPtr;
typedef boost::shared_ptr<ActionExecutionMode> ActionExecutionModePtr;
typedef boost::shared_ptr<GenericActionCommand> GenericActionCommandPtr;
typedef boost::shared_ptr<ErrorCollector> ErrorCollectorPtr;
typedef boost::shared_ptr<WindowLocation> WindowLocationPtr;
typedef boost::shared_ptr<DashboardProperties> DashboardPropertiesPtr;
typedef boost::shared_ptr<Action> ActionPtr;
typedef boost::shared_ptr<ActionDirectory> ActionDirectoryPtr;
typedef boost::shared_ptr<VariableGetter> VariableGetterPtr;
typedef boost::shared_ptr<VariableSetter> VariableSetterPtr;
typedef boost::shared_ptr<EventEnrichmentRule> EventEnrichmentRulePtr;
typedef boost::shared_ptr<GenericActionResponse> GenericActionResponsePtr;
typedef boost::shared_ptr<GenericActionCommand> GenericActionCommandPtr;
typedef boost::shared_ptr<ActionLocator> ActionLocatorPtr;
typedef boost::shared_ptr<ActionExecutionMode> ActionExecutionModePtr;
//typedef boost::shared_ptr<template <class L> ActionDirectory<L>> ActionDirectoryPtr;
typedef boost::shared_ptr<ServerActionInput> ServerActionInputPtr;
typedef boost::shared_ptr<ErrorCollector> ErrorCollectorPtr;
typedef boost::shared_ptr<ActionInitializer> ActionInitializerPtr;
typedef boost::shared_ptr< ResourceMask<AgObjectPtr> > ResourceMaskPtr;
typedef boost::shared_ptr<BasicActionDefinition> BasicActionDefinitionPtr;
typedef boost::shared_ptr<BatchAction> BatchActionPtr;
typedef boost::shared_ptr<TreeMask> TreeMaskPtr;
typedef boost::shared_ptr<EntityReference> EntityReferencePtr;
typedef boost::shared_ptr<WindowLocation> WindowLocationPtr;
typedef boost::shared_ptr<DashboardProperties> DashboardPropertiesPtr;
typedef boost::shared_ptr<ResourceBundle> ResourceBundlePtr;
typedef boost::shared_ptr<Locale> LocalePtr;
typedef boost::shared_ptr<OutgoingAggreGateCommand> OutgoingAggreGateCommandPtr;
typedef boost::shared_ptr<ContextEventListenerInfo> ContextEventListenerInfoPtr;
typedef boost::shared_ptr<CommandParser> CommandParserPtr;
typedef boost::shared_ptr<IncomingAggreGateCommand> IncomingAggreGateCommandPtr;
typedef boost::shared_ptr<BlockingChannel> BlockingChannelPtr;
typedef boost::shared_ptr<ContextEventListenerSet> ContextEventListenerSetPtr;
typedef boost::shared_ptr<PermissionType> PermissionTypePtr;
typedef boost::shared_ptr<RemoteServer> RemoteServerPtr;
typedef boost::shared_ptr<AgentContext> AgentContextPtr;
typedef boost::shared_ptr<AgentContextManager> AgentContextManagerPtr;
typedef boost::shared_ptr<BindingProvider> BindingProviderPtr;
typedef boost::shared_ptr<CallerControllerSelector> CallerControllerSelectorPtr;
typedef boost::shared_ptr<ChangeCache> ChangeCachePtr;
typedef boost::shared_ptr<BindingProcessor> BindingProcessorPtr;
typedef boost::shared_ptr<EvaluationOptions> EvaluationOptionsPtr;
typedef boost::shared_ptr<ReferenceListener> ReferenceListenerPtr;
typedef boost::shared_ptr<Exception> ExceptionPtr;
typedef boost::shared_ptr<Command> CommandPtr;
typedef boost::shared_ptr<CommandParserListener> CommandParserListenerPtr;
typedef boost::shared_ptr< AbstractDeviceController<void*,void*> > AbstractDeviceControllerPtr;
typedef boost::shared_ptr<CommandProcessorStatistics> CommandProcessorStatisticsPtr;
typedef boost::shared_ptr< AsyncCommandProcessor<AgObjectPtr,AgObjectPtr,AgObjectPtr> > AsyncCommandProcessorPtr;
typedef boost::shared_ptr<PluginDirector> PluginDirectorPtr;
typedef boost::shared_ptr<GroupContext> GroupContextPtr;
typedef boost::shared_ptr<DeviceAssetDefinition> DeviceAssetDefinitionPtr;
typedef boost::shared_ptr<DeviceContext> DeviceContextPtr;
typedef boost::shared_ptr<SynchronizationParameters> SynchronizationParametersPtr;
typedef boost::shared_ptr<SettingSynchronizationOptions> SettingSynchronizationOptionsPtr;
typedef boost::shared_ptr<DeviceSettingStatus> DeviceSettingStatusPtr;
typedef boost::shared_ptr<SynchronizationHandler> SynchronizationHandlerPtr;
typedef boost::shared_ptr<SynchronizationResult> SynchronizationResultPtr;
typedef boost::shared_ptr<DiscoveryProvider> DiscoveryProviderPtr;
typedef boost::shared_ptr<DeviceRecommendation> DeviceRecommendationPtr;
typedef boost::shared_ptr<DiscoverableServiceDefinition> DiscoverableServiceDefinitionPtr;
typedef boost::shared_ptr<DiscoveryResultItem> DiscoveryResultItemPtr;
typedef boost::shared_ptr<DiscoverableService> DiscoverableServicePtr;
typedef boost::shared_ptr<ServerContext> ServerContextPtr;
typedef boost::shared_ptr<BasePlugin> BasePluginPtr;
typedef boost::shared_ptr<AggreGateDevice> AggreGateDevicePtr;
typedef boost::shared_ptr<UserSettings> UserSettingsPtr;
typedef boost::shared_ptr<FormatCache> FormatCachePtr;
typedef boost::shared_ptr<RemoteContextManager> RemoteContextManagerPtr;
typedef boost::shared_ptr<EntityRelatedActionDescriptor> EntityRelatedActionDescriptorPtr;
typedef boost::shared_ptr< AbstractAggreGateDeviceController<AgObject,AgObject> > AbstractAggreGateDeviceControllerPtr;
typedef boost::shared_ptr< ProxyContext<AgObjectPtr> > ProxyContextPtr;
typedef boost::shared_ptr<EntityRelatedActionDescriptor> EntityRelatedActionDescriptorPtr;
typedef boost::shared_ptr<URI> URI_Ptr;
typedef boost::shared_ptr<EditDataMerger> EditDataMergerPtr;
typedef boost::shared_ptr<DashboardProperties> DashboardPropertiesPtr;
typedef boost::shared_ptr<EntityList> EntityListPtr;
typedef boost::shared_ptr<ExecutorService> ExecutorServicePtr;
typedef boost::shared_ptr<EventDispatcher> EventDispatcherPtr;
typedef boost::shared_ptr<CompatibilityConverter> CompatibilityConverterPtr;
typedef boost::shared_ptr<Color> ColorPtr;
typedef boost::shared_ptr<ReferenceWriter> ReferenceWriterPtr;
typedef boost::shared_ptr<UncheckedCallerController> UncheckedCallerControllerPtr;
typedef boost::shared_ptr<ExpressionParserVisitor> ExpressionParserVisitorPtr;
typedef boost::shared_ptr<DefaultRequestController> DefaultRequestControllerPtr;
typedef boost::shared_ptr<ReferencesFinderVisitor> ReferencesFinderVisitorPtr;
typedef boost::shared_ptr<ExpressionParser> ExpressionParserPtr;
//typedef boost::shared_ptr<>;
//typedef boost::shared_ptr<>;
//typedef boost::shared_ptr<>;
//typedef boost::shared_ptr<>;
//typedef boost::shared_ptr<>;
//typedef boost::shared_ptr<>;
//typedef boost::shared_ptr<>;
//typedef boost::shared_ptr<>;
//typedef boost::shared_ptr<>;
//typedef boost::shared_ptr<>;
#endif

