// Generated from /aggregate_sdk_5.11.00/src/com/tibbo/aggregate/common/server/UtilitiesContextConstants.java

#ifndef UtilitiesContextConstantsH
#define UtilitiesContextConstantsH


#include "server/ServerContextConstants.h"

class UtilitiesContextConstants
{
  public:

	static const int AGGREGATE_SORT_PRIORITY_PERIODS=0;
    static const int AGGREGATE_SORT_PRIORITY_CONTEXTS = 1;


    static const std::string F_DEBUG;
    static const std::string F_VARIABLE_ACTIONS;
    static const std::string F_EVENT_ACTIONS;
    static const std::string F_INIT_ACTIONS;
    static const std::string F_GET_DATA;
    static const std::string F_GET_FORMAT;
    static const std::string F_CHART_DATA;
    static const std::string F_ACTIONS_BY_MASK;
    static const std::string F_EVENTS_BY_MASK;
    static const std::string F_VARIABLES_BY_MASK;
    static const std::string F_EVENT_FIELDS;
    static const std::string F_VARIABLE_FIELDS;
    static const std::string F_VARIABLE_HISTORY;
    static const std::string F_STATISTICS;
    static const std::string F_RAW_STATISTICS;
    static const std::string F_TOPOLOGY;
    static const std::string F_DELETE_STATISTICS;
    static const std::string F_FILL_STATISTICS_FROM_HISTORY;
    static const std::string F_UPDATE_HOST;
    static const std::string F_SEND_SMS;
    static const std::string F_SEND_MAIL;
    static const std::string F_CHECK_MAIL;
    static const std::string F_ACTION_EXECUTION_PARAMETERS;
    static const std::string F_USERS;
    static const std::string F_VARIABLE_INFO;
    static const std::string F_EVENT_INFO;
    static const std::string F_EXECUTE;
    static const std::string F_LIST_VARIABLES;
    static const std::string F_SELECTION_VALUES;
    static const std::string F_SUMMARY;
    static const std::string A_VARIABLE_HISTORY;
    static const std::string A_VARIABLE_INFO;
    static const std::string A_EVENT_INFO;
    static const std::string A_SHOW_DATA;
    static const std::string FIF_INIT_ACTIONS_CONTEXT;
    static const std::string FIF_INIT_ACTIONS_ACTION_NAME;
    static const std::string FIF_INIT_ACTIONS_PARAMETERS;
    static const std::string FIF_GET_DATA_ID;
    static const std::string FIF_GET_FORMAT_ID;
    static const std::string FIF_TOPOLOGY_PROVIDER;
    static const std::string FIF_TOPOLOGY_NODE_MASK;
    static const std::string FIF_TOPOLOGY_TOPOLOGY_EXPRESSION;
    static const std::string FIF_TOPOLOGY_SOURCE_EXPRESSION;
    static const std::string FIF_TOPOLOGY_TARGET_EXPRESSION;
    static const std::string FIF_TOPOLOGY_DESCRIPTION_EXPRESSION;
    static const std::string FIF_TOPOLOGY_COLOR_EXPRESSION;
    static const std::string FIF_TOPOLOGY_TYPE_EXPRESSION;
    static const std::string FIF_TOPOLOGY_INTERFACE_EXPRESSION;
    static const std::string FIF_TOPOLOGY_DIRECTED_EXPRESSION;
    static const std::string FIF_TOPOLOGY_WIDTH_EXPRESSION;
    static const std::string FIF_TOPOLOGY_LINK_DESCRIPTION_EXPRESSION;
    static const std::string FIF_TOPOLOGY_LINK_COLOR_EXPRESSION;
    static const std::string FIF_VARIABLES_BY_MASK_MASK;
    static const std::string FIF_VARIABLES_BY_MASK_GROUP;
    static const std::string FIF_EXECUTE_COMMAND;
    static const std::string FIF_EXECUTE_DIRECTORY;
    static const std::string FIF_EVENTS_BY_MASK_MASK;
    static const std::string FIF_EVENTS_BY_MASK_ALLOW_ALL;
    static const std::string FIF_ACTIONS_BY_MASK_MASK;
    static const std::string FIF_ACTIONS_BY_MASK_INCLUDE_NON_HEADLESS;
    static const std::string FIF_ACTION_EXECUTION_PARAMETERS_MASK;
    static const std::string FIF_ACTION_EXECUTION_PARAMETERS_ACTION;
    static const std::string FIF_ACTION_EXECUTION_PARAMETERS_ORIGINAL;
    static const std::string FIF_ACTION_EXECUTION_PARAMETERS_INTERACTIVE;
    static const std::string FIF_EVENT_FIELDS_MASK;
    static const std::string FIF_EVENT_FIELDS_EVENT;
    static const std::string FIF_VARIABLE_FIELDS_MASK;
    static const std::string FIF_VARIABLE_FIELDS_VARIABLE;
    static const std::string FIF_SEND_MAIL_RECIPIENTS;
    static const std::string FIF_SEND_MAIL_SUBJECT;
    static const std::string FIF_SEND_MAIL_MESSAGE;
    static const std::string FIF_SEND_MAIL_HTML;
    static const std::string FIF_SEND_SMS_RECIPIENT;
    static const std::string FIF_SEND_SMS_MESSAGE;
    static const std::string FIF_UPDATE_HOST_HOST;
    static const std::string FIF_UPDATE_HOST_IP;
    static const std::string FIF_UPDATE_HOST_REMOVE;
    static const std::string FIF_VARIABLE_HISTORY_CONTEXT;
    static const std::string FIF_VARIABLE_HISTORY_VARIABLE;
    static const std::string FIF_VARIABLE_HISTORY_FROM_DATE;
    static const std::string FIF_VARIABLE_HISTORY_TO_DATE;
    static const std::string FIF_VARIABLE_HISTORY_DATA_AS_TABLE;
    static const std::string FIF_VARIABLE_HISTORY_LIMIT;
    static const std::string FIF_VARIABLE_HISTORY_SORT_ASCENDING;
    static const std::string FIF_VARIABLE_INFO_CONTEXT;
    static const std::string FIF_VARIABLE_INFO_VARIABLE;
    static const std::string FIF_RAW_STATISTICS_CONTEXT;
    static const std::string FIF_RAW_STATISTICS_NAME;
    static const std::string FIF_EVENT_INFO_CONTEXT;
    static const std::string FIF_EVENT_INFO_EVENT;
    static const std::string FIF_LIST_VARIABLES_GROUP;
    static const std::string FIF_LIST_VARIABLES_MASK;
    static const std::string FOF_LIST_VARIABLES_CONTEXT;
    static const std::string FOF_LIST_VARIABLES_VARIABLE;
    static const std::string FOF_LIST_VARIABLES_VALUE;
    static const std::string FIF_SELECTION_VALUES_TABLE_EXPRESSION;
    static const std::string FIF_SELECTION_VALUES_VALUE_EXPRESSION;
    static const std::string FIF_SELECTION_VALUES_DESCRIPTION_EXPRESSSION;
    static const std::string FIF_STATISTICS_MASK;
    static const std::string FIF_STATISTICS_CHANNEL;
    static const std::string FIF_STATISTICS_KEY;
    static const std::string FIF_STATISTICS_PERIOD;
    static const std::string FIF_STATISTICS_FULL;
    static const std::string FIF_STATISTICS_AVERAGE;
    static const std::string FIF_STATISTICS_MINIMUM;
    static const std::string FIF_STATISTICS_MAXIMUM;
    static const std::string FIF_STATISTICS_SUM;
    static const std::string FIF_STATISTICS_FIRST;
    static const std::string FIF_STATISTICS_LAST;
    static const std::string FOF_STATISTICS_CONTEXT;
    static const std::string FOF_STATISTICS_START;
    static const std::string FOF_STATISTICS_END;
    static const std::string FOF_STATISTICS_KEY;
    static const std::string FOF_STATISTICS_AVERAGE;
    static const std::string FOF_STATISTICS_MINIMUM;
    static const std::string FOF_STATISTICS_MAXIMUM;
    static const std::string FOF_STATISTICS_SUM;
    static const std::string FOF_STATISTICS_FIRST;
    static const std::string FOF_STATISTICS_LAST;
    static const std::string FOF_INIT_ACTIONS_ACTION_ID;
    static const std::string FOF_GET_DATA_DATA;
    static const std::string FOF_GET_FORMAT_DATA;
    static const std::string FIF_SUMMARY_SERIES_NAME;
    static const std::string FIF_SUMMARY_SERIES_DESCRIPTION;
    static const std::string FIF_SUMMARY_START_DATE;
    static const std::string FIF_SUMMARY_END_DATE;
    static const std::string FIF_SUMMARY_MASKS;
    static const std::string FIF_SUMMARY_ENTITY;
    static const std::string FIF_SUMMARY_ENTITY_TYPE;
    static const std::string FIF_SUMMARY_EXPRESSION;
    static const std::string FIF_SUMMARY_DATE_EXPRESSION;
    static const std::string FIF_SUMMARY_GROUPING;
    static const std::string FIF_SUMMARY_AGGREGATION;
    static const std::string FIF_SUMMARY_CHANGE_TYPE;
    static const std::string FIF_SUMMARY_OUT_OF_RANGE_VALUES_HANDLING;
    static const std::string FIF_SUMMARY_MIN_VALUE;
    static const std::string FIF_SUMMARY_MAX_VALUE;
    static const std::string FIF_SUMMARY_SHOW_DETAILS;
    static const std::string FIF_SUMMARY_SHOW_TOTALS;
    static const std::string FIF_SUMMARY_SORT_PRIORITY;
    static const std::string FIF_SUMMARY_TIME_ZONE;
    static const std::string FOF_SUMMARY_PERIOD_NAME;
    static const std::string FOF_SUMMARY_PERIOD_START;
    static const std::string FOF_SUMMARY_PERIOD_MIDDLE;
    static const std::string FOF_SUMMARY_PERIOD_END;
    static const std::string FOF_SUMMARY_CONTEXT;


};


  const std::string UtilitiesContextConstants::F_DEBUG = "debug";
  const std::string UtilitiesContextConstants::F_VARIABLE_ACTIONS = "variableActions";
  const std::string UtilitiesContextConstants::F_EVENT_ACTIONS = "eventActions";
  const std::string UtilitiesContextConstants::F_INIT_ACTIONS = "initActions";
  const std::string UtilitiesContextConstants::F_GET_DATA = "getData";
  const std::string UtilitiesContextConstants::F_GET_FORMAT = "getFormat";
  const std::string UtilitiesContextConstants::F_CHART_DATA = "chartData";
  const std::string UtilitiesContextConstants::F_ACTIONS_BY_MASK = "actionsByMask";
  const std::string UtilitiesContextConstants::F_EVENTS_BY_MASK = "eventsByMask";
  const std::string UtilitiesContextConstants::F_VARIABLES_BY_MASK = "variablesByMask";
  const std::string UtilitiesContextConstants::F_EVENT_FIELDS = "eventFields";
  const std::string UtilitiesContextConstants::F_VARIABLE_FIELDS = "variableFields";
  const std::string UtilitiesContextConstants::F_VARIABLE_HISTORY = "variableHistory";
  const std::string UtilitiesContextConstants::F_STATISTICS = "statistics";
  const std::string UtilitiesContextConstants::F_RAW_STATISTICS = "rawStatistics";
  const std::string UtilitiesContextConstants::F_TOPOLOGY = "topology";
  const std::string UtilitiesContextConstants::F_DELETE_STATISTICS = "deleteStatistics";
  const std::string UtilitiesContextConstants::F_FILL_STATISTICS_FROM_HISTORY = "fillStatisticsFromHistory";
  const std::string UtilitiesContextConstants::F_UPDATE_HOST = "updateHost";
  const std::string UtilitiesContextConstants::F_SEND_SMS = "sendSms";
  const std::string UtilitiesContextConstants::F_SEND_MAIL = "sendMail";
  const std::string UtilitiesContextConstants::F_CHECK_MAIL = "checkMail";
  const std::string UtilitiesContextConstants::F_ACTION_EXECUTION_PARAMETERS = "actionExecutionParameters";
  const std::string UtilitiesContextConstants::F_USERS = "users";
  const std::string UtilitiesContextConstants::F_VARIABLE_INFO = "variableInfo";
  const std::string UtilitiesContextConstants::F_EVENT_INFO = "eventInfo";
  const std::string UtilitiesContextConstants::F_EXECUTE = "execute";
  const std::string UtilitiesContextConstants::F_LIST_VARIABLES = "listVariables";
  const std::string UtilitiesContextConstants::F_SELECTION_VALUES = "selectionValues";
  const std::string UtilitiesContextConstants::F_SUMMARY = "summary";
  
  const std::string UtilitiesContextConstants::A_VARIABLE_HISTORY = "variableHistory";
  const std::string UtilitiesContextConstants::A_VARIABLE_INFO = "variableInfo";
  const std::string UtilitiesContextConstants::A_EVENT_INFO = "eventInfo";
  const std::string UtilitiesContextConstants::A_SHOW_DATA = "showData";
  
  const std::string UtilitiesContextConstants::FIF_INIT_ACTIONS_CONTEXT = "context";
  const std::string UtilitiesContextConstants::FIF_INIT_ACTIONS_ACTION_NAME = ServerContextConstants::FIF_INIT_ACTION_ACTION_NAME;
  const std::string UtilitiesContextConstants::FIF_INIT_ACTIONS_PARAMETERS =  ServerContextConstants::FIF_INIT_ACTION_INITIAL_PARAMETERS;
  const std::string UtilitiesContextConstants::FIF_GET_DATA_ID = "id";
  const std::string UtilitiesContextConstants::FIF_GET_FORMAT_ID = "id";
  const std::string UtilitiesContextConstants::FIF_TOPOLOGY_PROVIDER = "provider";
  const std::string UtilitiesContextConstants::FIF_TOPOLOGY_NODE_MASK = "nodeMask";
  const std::string UtilitiesContextConstants::FIF_TOPOLOGY_TOPOLOGY_EXPRESSION = "topologyExpression";
  const std::string UtilitiesContextConstants::FIF_TOPOLOGY_SOURCE_EXPRESSION = "sourceExpression";
  const std::string UtilitiesContextConstants::FIF_TOPOLOGY_TARGET_EXPRESSION = "targetExpression";
  const std::string UtilitiesContextConstants::FIF_TOPOLOGY_DESCRIPTION_EXPRESSION = "descriptionExpression";
  const std::string UtilitiesContextConstants::FIF_TOPOLOGY_COLOR_EXPRESSION = "colorExpression";
  const std::string UtilitiesContextConstants::FIF_TOPOLOGY_TYPE_EXPRESSION = "typeExpression";
  const std::string UtilitiesContextConstants::FIF_TOPOLOGY_INTERFACE_EXPRESSION = "interfaceExpression";
  const std::string UtilitiesContextConstants::FIF_TOPOLOGY_DIRECTED_EXPRESSION = "directedExpression";
  const std::string UtilitiesContextConstants::FIF_TOPOLOGY_WIDTH_EXPRESSION = "widthExpression";
  const std::string UtilitiesContextConstants::FIF_TOPOLOGY_LINK_DESCRIPTION_EXPRESSION = "linkDescriptionExpression";
  const std::string UtilitiesContextConstants::FIF_TOPOLOGY_LINK_COLOR_EXPRESSION = "linkColorExpression";
  const std::string UtilitiesContextConstants::FIF_VARIABLES_BY_MASK_MASK = "mask";
  const std::string UtilitiesContextConstants::FIF_VARIABLES_BY_MASK_GROUP = "group";
  const std::string UtilitiesContextConstants::FIF_EXECUTE_COMMAND = "command";
  const std::string UtilitiesContextConstants::FIF_EXECUTE_DIRECTORY = "directory";
  const std::string UtilitiesContextConstants::FIF_EVENTS_BY_MASK_MASK = "mask";
  const std::string UtilitiesContextConstants::FIF_EVENTS_BY_MASK_ALLOW_ALL = "allowAll";
  const std::string UtilitiesContextConstants::FIF_ACTIONS_BY_MASK_MASK = "mask";
  const std::string UtilitiesContextConstants::FIF_ACTIONS_BY_MASK_INCLUDE_NON_HEADLESS = "includeNonHeadless";
  const std::string UtilitiesContextConstants::FIF_ACTION_EXECUTION_PARAMETERS_MASK = "mask";
  const std::string UtilitiesContextConstants::FIF_ACTION_EXECUTION_PARAMETERS_ACTION = "action";
  const std::string UtilitiesContextConstants::FIF_ACTION_EXECUTION_PARAMETERS_ORIGINAL = "original";
  const std::string UtilitiesContextConstants::FIF_ACTION_EXECUTION_PARAMETERS_INTERACTIVE = "interactive";
  const std::string UtilitiesContextConstants::FIF_EVENT_FIELDS_MASK = "mask";
  const std::string UtilitiesContextConstants::FIF_EVENT_FIELDS_EVENT = "event";
  const std::string UtilitiesContextConstants::FIF_VARIABLE_FIELDS_MASK = "mask";
  const std::string UtilitiesContextConstants::FIF_VARIABLE_FIELDS_VARIABLE = "variable";
  const std::string UtilitiesContextConstants::FIF_SEND_MAIL_RECIPIENTS = "recipients";
  const std::string UtilitiesContextConstants::FIF_SEND_MAIL_SUBJECT = "subject";
  const std::string UtilitiesContextConstants::FIF_SEND_MAIL_MESSAGE = "message";
  const std::string UtilitiesContextConstants::FIF_SEND_MAIL_HTML = "html";
  const std::string UtilitiesContextConstants::FIF_SEND_SMS_RECIPIENT = "recipient";
  const std::string UtilitiesContextConstants::FIF_SEND_SMS_MESSAGE = "message";
  const std::string UtilitiesContextConstants::FIF_UPDATE_HOST_HOST = "host";
  const std::string UtilitiesContextConstants::FIF_UPDATE_HOST_IP = "ip";
  const std::string UtilitiesContextConstants::FIF_UPDATE_HOST_REMOVE = "remove";
  const std::string UtilitiesContextConstants::FIF_VARIABLE_HISTORY_CONTEXT = "context";
  const std::string UtilitiesContextConstants::FIF_VARIABLE_HISTORY_VARIABLE = "variable";
  const std::string UtilitiesContextConstants::FIF_VARIABLE_HISTORY_FROM_DATE = "fromDate";
  const std::string UtilitiesContextConstants::FIF_VARIABLE_HISTORY_TO_DATE = "toDate";
  const std::string UtilitiesContextConstants::FIF_VARIABLE_HISTORY_DATA_AS_TABLE = "dataAsTable";
  const std::string UtilitiesContextConstants::FIF_VARIABLE_HISTORY_LIMIT = "limit";
  const std::string UtilitiesContextConstants::FIF_VARIABLE_HISTORY_SORT_ASCENDING = "sortAscending";
  const std::string UtilitiesContextConstants::FIF_VARIABLE_INFO_CONTEXT = "context";
  const std::string UtilitiesContextConstants::FIF_VARIABLE_INFO_VARIABLE = "variable";
  const std::string UtilitiesContextConstants::FIF_RAW_STATISTICS_CONTEXT = "context";
  const std::string UtilitiesContextConstants::FIF_RAW_STATISTICS_NAME = "name";
  const std::string UtilitiesContextConstants::FIF_EVENT_INFO_CONTEXT = "context";
  const std::string UtilitiesContextConstants::FIF_EVENT_INFO_EVENT = "event";
  const std::string UtilitiesContextConstants::FIF_LIST_VARIABLES_GROUP = "group";
  const std::string UtilitiesContextConstants::FIF_LIST_VARIABLES_MASK = "mask";
  const std::string UtilitiesContextConstants::FOF_LIST_VARIABLES_CONTEXT = "context";
  const std::string UtilitiesContextConstants::FOF_LIST_VARIABLES_VARIABLE = "variable";
  const std::string UtilitiesContextConstants::FOF_LIST_VARIABLES_VALUE = "value";
  const std::string UtilitiesContextConstants::FIF_SELECTION_VALUES_TABLE_EXPRESSION = "tableExpression";
  const std::string UtilitiesContextConstants::FIF_SELECTION_VALUES_VALUE_EXPRESSION = "valueExpression";
  const std::string UtilitiesContextConstants::FIF_SELECTION_VALUES_DESCRIPTION_EXPRESSSION = "descriptionExpresssion";
  const std::string UtilitiesContextConstants::FIF_STATISTICS_MASK = "mask";
  const std::string UtilitiesContextConstants::FIF_STATISTICS_CHANNEL = "channel";
  const std::string UtilitiesContextConstants::FIF_STATISTICS_KEY = "key";
  const std::string UtilitiesContextConstants::FIF_STATISTICS_PERIOD = "period";
  const std::string UtilitiesContextConstants::FIF_STATISTICS_FULL = "full";
  const std::string UtilitiesContextConstants::FIF_STATISTICS_AVERAGE = "average";
  const std::string UtilitiesContextConstants::FIF_STATISTICS_MINIMUM = "minimum";
  const std::string UtilitiesContextConstants::FIF_STATISTICS_MAXIMUM = "maximum";
  const std::string UtilitiesContextConstants::FIF_STATISTICS_SUM = "sum";
  const std::string UtilitiesContextConstants::FIF_STATISTICS_FIRST = "first";
  const std::string UtilitiesContextConstants::FIF_STATISTICS_LAST = "last";
  
  const std::string UtilitiesContextConstants::FOF_STATISTICS_CONTEXT = "context";
  const std::string UtilitiesContextConstants::FOF_STATISTICS_START = "start";
  const std::string UtilitiesContextConstants::FOF_STATISTICS_END = "end";
  const std::string UtilitiesContextConstants::FOF_STATISTICS_KEY = "key";
  const std::string UtilitiesContextConstants::FOF_STATISTICS_AVERAGE = "average";
  const std::string UtilitiesContextConstants::FOF_STATISTICS_MINIMUM = "minimum";
  const std::string UtilitiesContextConstants::FOF_STATISTICS_MAXIMUM = "maximum";
  const std::string UtilitiesContextConstants::FOF_STATISTICS_SUM = "sum";
  const std::string UtilitiesContextConstants::FOF_STATISTICS_FIRST = "first";
  const std::string UtilitiesContextConstants::FOF_STATISTICS_LAST = "last";
  
  const std::string UtilitiesContextConstants::FOF_INIT_ACTIONS_ACTION_ID = "actionId";
  const std::string UtilitiesContextConstants::FOF_GET_DATA_DATA = "data";
  const std::string UtilitiesContextConstants::FOF_GET_FORMAT_DATA = "data";
  
  const std::string UtilitiesContextConstants::FIF_SUMMARY_SERIES_NAME = "seriesName";
  const std::string UtilitiesContextConstants::FIF_SUMMARY_SERIES_DESCRIPTION = "seriesDescription";
  const std::string UtilitiesContextConstants::FIF_SUMMARY_START_DATE = "startDate";
  const std::string UtilitiesContextConstants::FIF_SUMMARY_END_DATE = "endDate";
  const std::string UtilitiesContextConstants::FIF_SUMMARY_MASKS = "masks";
  const std::string UtilitiesContextConstants::FIF_SUMMARY_ENTITY = "entity";
  const std::string UtilitiesContextConstants::FIF_SUMMARY_ENTITY_TYPE = "entityType";
  const std::string UtilitiesContextConstants::FIF_SUMMARY_EXPRESSION = "expression";
  const std::string UtilitiesContextConstants::FIF_SUMMARY_DATE_EXPRESSION = "dateExpression";
  const std::string UtilitiesContextConstants::FIF_SUMMARY_GROUPING = "grouping";
  const std::string UtilitiesContextConstants::FIF_SUMMARY_AGGREGATION = "aggregation";
  const std::string UtilitiesContextConstants::FIF_SUMMARY_CHANGE_TYPE = "changeType";
  const std::string UtilitiesContextConstants::FIF_SUMMARY_OUT_OF_RANGE_VALUES_HANDLING = "outOfRangeValuesHandling";
  const std::string UtilitiesContextConstants::FIF_SUMMARY_MIN_VALUE = "minValue";
  const std::string UtilitiesContextConstants::FIF_SUMMARY_MAX_VALUE = "maxValue";
  const std::string UtilitiesContextConstants::FIF_SUMMARY_SHOW_DETAILS = "showDetails";
  const std::string UtilitiesContextConstants::FIF_SUMMARY_SHOW_TOTALS = "showTotals";
  const std::string UtilitiesContextConstants::FIF_SUMMARY_SORT_PRIORITY = "sortPriority";
  const std::string UtilitiesContextConstants::FIF_SUMMARY_TIME_ZONE = "timeZone";
  
  const std::string UtilitiesContextConstants::FOF_SUMMARY_PERIOD_NAME = "periodName";
  const std::string UtilitiesContextConstants::FOF_SUMMARY_PERIOD_START = "periodStart";
  const std::string UtilitiesContextConstants::FOF_SUMMARY_PERIOD_MIDDLE = "periodMiddle";
  const std::string UtilitiesContextConstants::FOF_SUMMARY_PERIOD_END = "periodEnd";
  const std::string UtilitiesContextConstants::FOF_SUMMARY_CONTEXT = "context";
  #endif