// Generated from /aggregate_sdk_5.11.00/src/com/tibbo/aggregate/common/expression/function/Functions.java

#pragma once

#include <com/tibbo/aggregate/common/expression/function/fwd-aggregate_sdk_5.11.00.h"
//#include <java/lang/fwd-aggregate_sdk_5.11.00.h"
//#include <java/lang/Object.h"



class function::Functions
    
{

public:
    typedef void super;

private:
    static const std::string ABS_;
    static const std::string ACOS_;
    static const std::string ASIN_;
    static const std::string ATAN_;
    static const std::string CBRT_;
    static const std::string CEIL_;
    static const std::string COS_;
    static const std::string COSH_;
    static const std::string E_;
    static const std::string EXP_;
    static const std::string EQ_;
    static const std::string FLOOR_;
    static const std::string GE_;
    static const std::string GT_;
    static const std::string LE_;
    static const std::string LOG_;
    static const std::string LOG10_;
    static const std::string LT_;
    static const std::string MIN_;
    static const std::string MAX_;
    static const std::string NE_;
    static const std::string PI_;
    static const std::string POW_;
    static const std::string RANDOM_;
    static const std::string ROUND_;
    static const std::string SIGNUM_;
    static const std::string SIN_;
    static const std::string SINH_;
    static const std::string SQRT_;
    static const std::string TAN_;
    static const std::string TANH_;
    static const std::string FORMAT_NUMBER_;
    static const std::string CONTAINS_;
    static const std::string ENDS_WITH_;
    static const std::string FORMAT_;
    static const std::string GROUPS_;
    static const std::string INDEX_;
    static const std::string IS_DIGIT_;
    static const std::string IS_LETTER_;
    static const std::string IS_LOWER_CASE_;
    static const std::string IS_UPPER_CASE_;
    static const std::string IS_WHITESPACE_;
    static const std::string LAST_INDEX_;
    static const std::string LENGTH_;
    static const std::string LOWER_;
    static const std::string REPLACE_;
    static const std::string SPLIT_;
    static const std::string STARTS_WITH_;
    static const std::string SUBSTRING_;
    static const std::string TRIM_;
    static const std::string UPPER_;
    static const std::string URL_DECODE_;
    static const std::string URL_ENCODE_;
    static const std::string DATE_;
    static const std::string DATE_ADD_;
    static const std::string DATE_DIFF_;
    static const std::string DAY_;
    static const std::string DAY_OF_WEEK_;
    static const std::string DAY_OF_YEAR_;
    static const std::string FORMAT_DATE_;
    static const std::string HOUR_;
    static const std::string MILLISECOND_;
    static const std::string MINUTE_;
    static const std::string MONTH_;
    static const std::string NOW_;
    static const std::string SECOND_;
    static const std::string PRINT_PERIOD_;
    static const std::string TIME_;
    static const std::string YEAR_;
    static const std::string BLUE_;
    static const std::string BRIGHTER_;
    static const std::string COLOR_;
    static const std::string DARKER_;
    static const std::string GREEN_;
    static const std::string RED_;
    static const std::string ADD_COLUMNS_;
    static const std::string ADD_RECORDS_;
    static const std::string ADJUST_RECORD_LIMITS_;
    static const std::string AGGREGATE_;
    static const std::string CELL_;
    static const std::string CLEAR_;
    static const std::string CONVERT_;
    static const std::string COPY_;
    static const std::string DESCRIBE_;
    static const std::string DESCRIPTION_;
    static const std::string ENCODE_;
    static const std::string FILTER_;
    static const std::string GET_FORMAT_;
    static const std::string HAS_FIELD_;
    static const std::string JOIN_;
    static const std::string PRINT_;
    static const std::string RECORDS_;
    static const std::string REMOVE_COLUMNS_;
    static const std::string REMOVE_RECORDS_;
    static const std::string SELECT_;
    static const std::string SET_;
    static const std::string SORT_;
    static const std::string SUBTABLE_;
    static const std::string TABLE_;
    static const std::string UNION_;
    static const std::string BOOLEAN_;
    static const std::string INTEGER_;
    static const std::string FLOAT_;
    static const std::string LONG_;
    static const std::string STRING_;
    static const std::string TIMESTAMP_;
    static const std::string AVAILABLE_;
    static const std::string CALL_FUNCTION_;
    static const std::string DC_;
    static const std::string DR_;
    static const std::string DT_;
    static const std::string EVENT_AVAILABLE_;
    static const std::string EVENT_FORMAT_;
    static const std::string FIRE_EVENT_;
    static const std::string FUNCTION_AVAILABLE_;
    static const std::string FUNCTION_INPUT_FORMAT_;
    static const std::string FUNCTION_OUTPUT_FORMAT_;
    static const std::string GET_VARIABLE_;
    static const std::string SET_VARIABLE_;
    static const std::string VARIABLE_AVAILABLE_;
    static const std::string VARIABLE_FORMAT_;
    static const std::string VARIABLE_READABLE_;
    static const std::string VARIABLE_WRITABLE_;
    static const std::string EVALUATE_;
    static const std::string LD_;
    static const std::string SLEEP_;
    static const std::string ST_;
    static const std::string TRACE_;
    static const std::string USER_;
    static const std::string XPATH_;
    static const std::string ABSOLUTE_;
    static const std::string EXPRESSION_EDITOR_OPTIONS_;
    static const std::string HAS_RESOLVER_;
    static const std::string GROUP_CONTEXT_RELATED_;
    static const std::string GROUP_DATA_TABLE_PROCESSING_;
    static const std::string GROUP_NUMBER_PROCESSING_;
    static const std::string GROUP_TYPE_CONVERSION_;
    static const std::string GROUP_DATE_TIME_PROCESSING_;
    static const std::string GROUP_COLOR_PROCESSING_;
    static const std::string GROUP_SYSTEM_;
    static const std::string GROUP_STRING_PROCESSING_;
    static const std::string GROUP_OTHER_;
    static const std::string HAS_VARIABLE_;
    static const std::string HAS_FUNCTION_;
    static const std::string HAS_EVENT_;

    // Generated

public:
    Functions();
protected:
    Functions(const ::default_init_tag&);


public:
    
    static void 
    static const std::string& ABS();
    static const std::string& ACOS();
    static const std::string& ASIN();
    static const std::string& ATAN();
    static const std::string& CBRT();
    static const std::string& CEIL();
    static const std::string& COS();
    static const std::string& COSH();
    static const std::string& E();
    static const std::string& EXP();
    static const std::string& EQ();
    static const std::string& FLOOR();
    static const std::string& GE();
    static const std::string& GT();
    static const std::string& LE();
    static const std::string& LOG();
    static const std::string& LOG10();
    static const std::string& LT();
    static const std::string& MIN();
    static const std::string& MAX();
    static const std::string& NE();
    static const std::string& PI();
    static const std::string& POW();
    static const std::string& RANDOM();
    static const std::string& ROUND();
    static const std::string& SIGNUM();
    static const std::string& SIN();
    static const std::string& SINH();
    static const std::string& SQRT();
    static const std::string& TAN();
    static const std::string& TANH();
    static const std::string& FORMAT_NUMBER();
    static const std::string& CONTAINS();
    static const std::string& ENDS_WITH();
    static const std::string& FORMAT();
    static const std::string& GROUPS();
    static const std::string& INDEX();
    static const std::string& IS_DIGIT();
    static const std::string& IS_LETTER();
    static const std::string& IS_LOWER_CASE();
    static const std::string& IS_UPPER_CASE();
    static const std::string& IS_WHITESPACE();
    static const std::string& LAST_INDEX();
    static const std::string& LENGTH();
    static const std::string& LOWER();
    static const std::string& REPLACE();
    static const std::string& SPLIT();
    static const std::string& STARTS_WITH();
    static const std::string& SUBSTRING();
    static const std::string& TRIM();
    static const std::string& UPPER();
    static const std::string& URL_DECODE();
    static const std::string& URL_ENCODE();
    static const std::string& DATE();
    static const std::string& DATE_ADD();
    static const std::string& DATE_DIFF();
    static const std::string& DAY();
    static const std::string& DAY_OF_WEEK();
    static const std::string& DAY_OF_YEAR();
    static const std::string& FORMAT_DATE();
    static const std::string& HOUR();
    static const std::string& MILLISECOND();
    static const std::string& MINUTE();
    static const std::string& MONTH();
    static const std::string& NOW();
    static const std::string& SECOND();
    static const std::string& PRINT_PERIOD();
    static const std::string& TIME();
    static const std::string& YEAR();
    static const std::string& BLUE();
    static const std::string& BRIGHTER();
    static const std::string& COLOR();
    static const std::string& DARKER();
    static const std::string& GREEN();
    static const std::string& RED();
    static const std::string& ADD_COLUMNS();
    static const std::string& ADD_RECORDS();
    static const std::string& ADJUST_RECORD_LIMITS();
    static const std::string& AGGREGATE();
    static const std::string& CELL();
    static const std::string& CLEAR();
    static const std::string& CONVERT();
    static const std::string& COPY();
    static const std::string& DESCRIBE();
    static const std::string& DESCRIPTION();
    static const std::string& ENCODE();
    static const std::string& FILTER();
    static const std::string& GET_FORMAT();
    static const std::string& HAS_FIELD();
    static const std::string& JOIN();
    static const std::string& PRINT();
    static const std::string& RECORDS();
    static const std::string& REMOVE_COLUMNS();
    static const std::string& REMOVE_RECORDS();
    static const std::string& SELECT();
    static const std::string& SET();
    static const std::string& SORT();
    static const std::string& SUBTABLE();
    static const std::string& TABLE();
    static const std::string& UNION();
    static const std::string& BOOLEAN();
    static const std::string& INTEGER();
    static const std::string& FLOAT();
    static const std::string& LONG();
    static const std::string& STRING();
    static const std::string& TIMESTAMP();
    static const std::string& AVAILABLE();
    static const std::string& CALL_FUNCTION();
    static const std::string& DC();
    static const std::string& DR();
    static const std::string& DT();
    static const std::string& EVENT_AVAILABLE();
    static const std::string& EVENT_FORMAT();
    static const std::string& FIRE_EVENT();
    static const std::string& FUNCTION_AVAILABLE();
    static const std::string& FUNCTION_INPUT_FORMAT();
    static const std::string& FUNCTION_OUTPUT_FORMAT();
    static const std::string& GET_VARIABLE();
    static const std::string& SET_VARIABLE();
    static const std::string& VARIABLE_AVAILABLE();
    static const std::string& VARIABLE_FORMAT();
    static const std::string& VARIABLE_READABLE();
    static const std::string& VARIABLE_WRITABLE();
    static const std::string& EVALUATE();
    static const std::string& LD();
    static const std::string& SLEEP();
    static const std::string& ST();
    static const std::string& TRACE();
    static const std::string& USER();
    static const std::string& XPATH();
    static const std::string& ABSOLUTE();
    static const std::string& EXPRESSION_EDITOR_OPTIONS();
    static const std::string& HAS_RESOLVER();
    static const std::string& GROUP_CONTEXT_RELATED();
    static const std::string& GROUP_DATA_TABLE_PROCESSING();
    static const std::string& GROUP_NUMBER_PROCESSING();
    static const std::string& GROUP_TYPE_CONVERSION();
    static const std::string& GROUP_DATE_TIME_PROCESSING();
    static const std::string& GROUP_COLOR_PROCESSING();
    static const std::string& GROUP_SYSTEM();
    static const std::string& GROUP_STRING_PROCESSING();
    static const std::string& GROUP_OTHER();
    static const std::string& HAS_VARIABLE();
    static const std::string& HAS_FUNCTION();
    static const std::string& HAS_EVENT();

private:
    ::java::lang::Class* getClass0();
};
